-- Generated by @chromatis/base. Edit sql/views/*.sql and sql/functions/*.sql, then regenerate.
-- Manual compatibility fix: older databases may have recorded 1.0.0 before users.enabled existed.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- sql/views/v_course_dto.sql
CREATE OR REPLACE VIEW v_course_dto AS
SELECT
  c.course_id                                                                   AS id,
  CASE WHEN cv.variant_short IS NOT NULL
       THEN s.subject_label || ' (' || cv.variant_short || ')'
       ELSE s.subject_label
  END                                                                            AS label,
  g.group_label                                                                  AS description,
  g.group_key,
  g.group_label,
  s.subject_id,
  s.subject_label,
  c.slug,
  c.icon,
  c.color,
  c.is_listed,
  c.is_public,
  c.registration_open_until,
  ARRAY[g.group_label, s.subject_label]                                          AS tags
FROM courses c
JOIN groups g           ON g.group_id   = c.group_id
JOIN subjects s         ON s.subject_id = c.subject_id
LEFT JOIN course_variants cv ON cv.variant_id = c.variant_id;

-- sql/views/v_user_dto.sql
CREATE OR REPLACE VIEW v_user_dto AS
SELECT
  u.id,
  u.role,
  u.group_key,
  COALESCE(
    ARRAY_AGG(uc.course_id) FILTER (WHERE uc.course_id IS NOT NULL),
    ARRAY[]::TEXT[]
  ) AS course_ids
FROM users u
LEFT JOIN user_courses uc ON uc.user_id = u.id
GROUP BY u.id, u.role, u.group_key;

-- sql/views/v_worksheets_by_chapter.sql
CREATE OR REPLACE VIEW v_worksheets_by_chapter AS
SELECT
  cw.course_id,
  cw.topic_id,
  cw.chapter_id,
  cw.worksheet_id,
  w.label,
  CASE
    WHEN w.worksheet_format IN ('pdf', 'pdfSolution')
    THEN CONCAT('/.generated/pdf/', c.subject_id, '/', cw.topic_id, '/', cw.chapter_id, '/worksheets/', cw.worksheet_id, '.pdf')
    ELSE CONCAT(c.slug, '/', t.href_slug, '/', ch.href_slug, '/', w.href_slug)
  END                 AS href,
  CASE
    WHEN w.worksheet_format = 'pdfSolution'
    THEN CONCAT('/.generated/pdf/', c.subject_id, '/', cw.topic_id, '/', cw.chapter_id, '/worksheets/', cw.worksheet_id, '-solution.pdf')
    ELSE NULL
  END                 AS solution_href,
  w.worksheet_format,
  cw.is_hidden,
  cw.is_solution_hidden,
  cw.display_order
FROM course_worksheets cw
JOIN worksheets w  ON w.worksheet_id  = cw.worksheet_id
JOIN courses c     ON c.course_id     = cw.course_id
JOIN topics t      ON t.topic_id      = cw.topic_id
JOIN chapters ch   ON ch.chapter_id   = cw.chapter_id;

-- sql/functions/check_and_record_attempt.sql
-- Rate limiting check and record attempt
CREATE OR REPLACE FUNCTION check_and_record_attempt(
  p_bucket_key TEXT,
  p_success    BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  v_bucket     public.auth_attempts%ROWTYPE;
  v_now        TIMESTAMPTZ := NOW();
  v_max        INTEGER     := 5;
  v_window     INTERVAL    := INTERVAL '15 minutes';
BEGIN
  IF p_success THEN
    DELETE FROM public.auth_attempts
    WHERE bucket_key = p_bucket_key;

    RETURN jsonb_build_object('allowed', true);
  END IF;

  SELECT *
  INTO v_bucket
  FROM public.auth_attempts
  WHERE bucket_key = p_bucket_key
  FOR UPDATE;

  IF NOT FOUND THEN
    BEGIN
      INSERT INTO public.auth_attempts (bucket_key, attempt_count, window_start)
      VALUES (p_bucket_key, 1, v_now);

      RETURN jsonb_build_object('allowed', true, 'attempts', 1);
    EXCEPTION
      WHEN unique_violation THEN
        SELECT *
        INTO v_bucket
        FROM public.auth_attempts
        WHERE bucket_key = p_bucket_key
        FOR UPDATE;
    END;
  END IF;

  IF v_bucket.locked_until IS NOT NULL AND v_bucket.locked_until > v_now THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'locked',
      'locked_until', v_bucket.locked_until
    );
  END IF;

  IF v_now - v_bucket.window_start > v_window THEN
    UPDATE public.auth_attempts
    SET attempt_count = 1,
        window_start = v_now,
        locked_until = NULL
    WHERE bucket_key = p_bucket_key;

    RETURN jsonb_build_object('allowed', true, 'attempts', 1);
  END IF;

  UPDATE public.auth_attempts
  SET attempt_count = attempt_count + 1,
      locked_until  = CASE
        WHEN attempt_count + 1 >= v_max THEN v_now + v_window
        ELSE NULL
      END
  WHERE bucket_key = p_bucket_key
  RETURNING attempt_count
  INTO v_bucket.attempt_count;

  IF v_bucket.attempt_count >= v_max THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'too_many_attempts',
      'attempts', v_bucket.attempt_count
    );
  END IF;

  RETURN jsonb_build_object('allowed', true, 'attempts', v_bucket.attempt_count);
END;
$$;

-- sql/functions/create_user_account.sql
-- Atomic user account creation
CREATE OR REPLACE FUNCTION create_user_account(
  p_user_id     TEXT,
  p_username TEXT,
  p_pin_hash    TEXT,
  p_group_key   TEXT,
  p_course_ids  TEXT[]
)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH inserted_user AS (
    INSERT INTO public.users (id, role, group_key, username, pin_hash)
    VALUES (p_user_id, 'user', p_group_key, p_username, p_pin_hash)
    RETURNING id
  ),
  requested_courses AS (
    SELECT DISTINCT requested.course_id
    FROM unnest(COALESCE(p_course_ids, ARRAY[]::TEXT[])) AS requested(course_id)
    WHERE requested.course_id IS NOT NULL
  )
  INSERT INTO public.user_courses (user_id, course_id)
  SELECT iu.id, rc.course_id
  FROM inserted_user iu
  JOIN requested_courses rc ON TRUE
  ON CONFLICT (user_id, course_id) DO NOTHING;
$$;

-- sql/functions/create_user_with_username.sql
-- Atomically generate a unique username and create the user account
CREATE OR REPLACE FUNCTION create_user_with_username(
  p_user_id   TEXT,
  p_pin_hash  TEXT,
  p_group_key TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_username        TEXT;
  v_attempts        INTEGER := 0;
  v_constraint_name TEXT;
BEGIN
  LOOP
    v_attempts := v_attempts + 1;

    IF v_attempts > 100 THEN
      RAISE EXCEPTION 'Failed to create user with a unique username after 100 attempts';
    END IF;

    v_username := public.generate_username();

    BEGIN
      PERFORM public.create_user_account(
        p_user_id,
        v_username,
        p_pin_hash,
        p_group_key,
        ARRAY[]::TEXT[]
      );

      RETURN v_username;
    EXCEPTION
      WHEN unique_violation THEN
        GET STACKED DIAGNOSTICS v_constraint_name = CONSTRAINT_NAME;

        IF v_constraint_name = 'users_username_key' THEN
          CONTINUE;
        END IF;

        RAISE;
    END;
  END LOOP;
END;
$$;

-- sql/functions/enroll_user_in_course.sql
-- Enroll a user in a course
CREATE OR REPLACE FUNCTION enroll_user_in_course(p_user_id TEXT, p_course_id TEXT)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  INSERT INTO public.user_courses (user_id, course_id)
  VALUES (p_user_id, p_course_id)
  ON CONFLICT (user_id, course_id) DO NOTHING;
$$;

-- sql/functions/generate_username.sql
-- Generate a username from a rotating word list and permuted 2-digit suffix
CREATE OR REPLACE FUNCTION generate_username()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  a          CONSTANT INTEGER := 31; -- gcd(31, 101) = 1
  b          CONSTANT INTEGER := 23; -- gcd(23, 99) = 1
  word_count CONSTANT INTEGER := 101; -- gcd(101, 99) = 1
  max_tries  CONSTANT INTEGER := word_count * 99;
  n          BIGINT;
  word_index INTEGER;
  word       TEXT;
  num        TEXT;
  v_username TEXT;
  i          INTEGER;
BEGIN
  FOR i IN 1..max_tries LOOP
    n := nextval('public.username_counter');

    word_index := ((a * n) % word_count)::INTEGER;

    SELECT uw.word
    INTO word
    FROM public.username_words uw
    WHERE uw.pos = word_index;

    IF word IS NULL THEN
      RAISE EXCEPTION 'Missing word at index % (must be contiguous 0..%)',
        word_index, word_count - 1;
    END IF;

    -- Permuted 2-digit number in range 01..99
    num := LPAD((((b * n) % 99) + 1)::TEXT, 2, '0');
    v_username := word || num;

    IF NOT EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.username = v_username
    ) THEN
      RETURN v_username;
    END IF;
  END LOOP;

  RAISE EXCEPTION 'No unused username available in current cycle (word_count=%)', word_count;
END;
$$;

-- sql/functions/get_course_access_groups.sql
-- Return courses grouped by access level for the current session context
CREATE OR REPLACE FUNCTION get_course_access_groups()
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
WITH session_context AS (
  SELECT
    current_setting('app.user_role', true) AS user_role,
    current_setting('app.user_id', true)   AS user_id,
    current_setting('app.group_key', true) AS group_key
),
course_access AS (
  SELECT
    c.id,
    c.is_listed,
    c.is_public,
    (
      sc.user_role = 'admin'
      OR c.group_key = sc.group_key
      OR uc.user_id IS NOT NULL
    ) AS is_accessible
  FROM public.v_course_dto c
  CROSS JOIN session_context sc
  LEFT JOIN public.user_courses uc
    ON uc.course_id = c.id
   AND uc.user_id = sc.user_id
)
SELECT jsonb_build_object(
  'public', COALESCE(
    jsonb_agg(ca.id ORDER BY ca.id)
      FILTER (WHERE ca.is_listed AND ca.is_public),
    '[]'::jsonb
  ),
  'accessible', COALESCE(
    jsonb_agg(ca.id ORDER BY ca.id)
      FILTER (WHERE ca.is_listed AND NOT ca.is_public AND ca.is_accessible),
    '[]'::jsonb
  ),
  'restricted', COALESCE(
    jsonb_agg(ca.id ORDER BY ca.id)
      FILTER (WHERE ca.is_listed AND NOT ca.is_public AND NOT ca.is_accessible),
    '[]'::jsonb
  ),
  'hidden', COALESCE(
    jsonb_agg(ca.id ORDER BY ca.id)
      FILTER (WHERE NOT ca.is_listed),
    '[]'::jsonb
  )
)
FROM course_access ca;
$$;

-- sql/functions/get_progress_dto.sql
-- Return full course progress tree as JSONB
CREATE OR REPLACE FUNCTION get_progress_dto(p_course_id TEXT)
RETURNS JSONB
LANGUAGE sql
STABLE
AS $$
WITH course_base AS (
  SELECT
    c.course_id,
    c.slug
  FROM public.courses c
  WHERE c.course_id = p_course_id
),
topic_rows AS (
  SELECT
    ct.course_id,
    ct.topic_id,
    t.label AS topic_label,
    CONCAT(cb.slug, '/', t.href_slug) AS topic_href,
    ct.status AS topic_status,
    ct.display_order AS topic_order
  FROM public.course_topics ct
  JOIN public.topics t
    ON t.topic_id = ct.topic_id
  JOIN course_base cb
    ON cb.course_id = ct.course_id
),
chapter_rows AS (
  SELECT
    cc.course_id,
    cc.topic_id,
    cc.chapter_id,
    ch.label AS chapter_label,
    CONCAT(cb.slug, '/', t.href_slug, '/', ch.href_slug) AS chapter_href,
    cc.status AS chapter_status,
    cc.display_order AS chapter_order
  FROM public.course_chapters cc
  JOIN public.chapters ch
    ON ch.chapter_id = cc.chapter_id
  JOIN public.topics t
    ON t.topic_id = cc.topic_id
  JOIN course_base cb
    ON cb.course_id = cc.course_id
),
current_ids AS (
  SELECT
    COALESCE(
      (SELECT tr.topic_id FROM topic_rows tr WHERE tr.topic_status = 'current'),
      ''
    ) AS current_topic_id,
    COALESCE(
      (SELECT cr.chapter_id FROM chapter_rows cr WHERE cr.chapter_status = 'current'),
      ''
    ) AS current_chapter_id
),
worksheets_by_chapter AS (
  SELECT
    w.course_id,
    w.topic_id,
    w.chapter_id,
    jsonb_agg(
      jsonb_build_object(
        'worksheetId', w.worksheet_id,
        'label', w.label,
        'href', w.href,
        'worksheetFormat', w.worksheet_format
      )
      ORDER BY w.display_order, w.worksheet_id
    ) AS worksheets
  FROM public.v_worksheets_by_chapter w
  WHERE w.course_id = p_course_id
    AND w.is_hidden = false
  GROUP BY w.course_id, w.topic_id, w.chapter_id
),
chapters_with_worksheets AS (
  SELECT
    cr.course_id,
    cr.topic_id,
    cr.chapter_order,
    cr.chapter_id,
    jsonb_build_object(
      'chapterId', cr.chapter_id,
      'label', cr.chapter_label,
      'href', cr.chapter_href,
      'status', cr.chapter_status,
      'worksheets', COALESCE(wbc.worksheets, '[]'::jsonb)
    ) AS chapter_obj
  FROM chapter_rows cr
  LEFT JOIN worksheets_by_chapter wbc
    ON wbc.course_id = cr.course_id
   AND wbc.topic_id = cr.topic_id
   AND wbc.chapter_id = cr.chapter_id
),
chapters_by_topic AS (
  SELECT
    cww.course_id,
    cww.topic_id,
    jsonb_agg(cww.chapter_obj ORDER BY cww.chapter_order, cww.chapter_id) AS chapters
  FROM chapters_with_worksheets cww
  GROUP BY cww.course_id, cww.topic_id
),
topics_with_chapters AS (
  SELECT
    tr.course_id,
    tr.topic_order,
    tr.topic_id,
    jsonb_build_object(
      'topicId', tr.topic_id,
      'label', tr.topic_label,
      'href', tr.topic_href,
      'status', tr.topic_status,
      'chapters', COALESCE(cbt.chapters, '[]'::jsonb)
    ) AS topic_obj
  FROM topic_rows tr
  LEFT JOIN chapters_by_topic cbt
    ON cbt.course_id = tr.course_id
   AND cbt.topic_id = tr.topic_id
),
topics_agg AS (
  SELECT
    twc.course_id,
    jsonb_agg(twc.topic_obj ORDER BY twc.topic_order, twc.topic_id) AS topics
  FROM topics_with_chapters twc
  GROUP BY twc.course_id
)
SELECT jsonb_build_object(
  'currentTopicId', ci.current_topic_id,
  'currentChapterId', ci.current_chapter_id,
  'topics', COALESCE(ta.topics, '[]'::jsonb)
)
FROM current_ids ci
LEFT JOIN topics_agg ta
  ON TRUE;
$$;

-- sql/functions/get_quiz_broadcast_data.sql
-- Returns the full quiz session row plus aggregate counts needed for Ably broadcasts.
-- SECURITY DEFINER bypasses RLS so this can be called via anonSQL from student-triggered
-- code paths (submitQuizResponse, joinQuizSession) without the student's RLS restrictions
-- corrupting the participant and response counts sent to the admin channel.

CREATE OR REPLACE FUNCTION get_quiz_broadcast_data(p_session_id TEXT)
RETURNS TABLE (
  session_id       TEXT,
  course_id        TEXT,
  phase            TEXT,
  questions        JSONB,
  current_index    INTEGER,
  timer_seconds    INTEGER,
  timer_started_at TIMESTAMPTZ,
  updated_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ,
  participant_count INTEGER,
  responses        JSON
)
SECURITY DEFINER
SET search_path = public
LANGUAGE sql
AS $$
  SELECT
    s.session_id,
    s.course_id,
    s.phase,
    s.questions,
    s.current_index,
    s.timer_seconds,
    s.timer_started_at,
    s.updated_at,
    s.created_at,
    (SELECT COUNT(*)::int FROM quiz_participants p WHERE p.session_id = s.session_id),
    COALESCE(
      (SELECT json_agg(r.selected)
       FROM quiz_responses r
       WHERE r.session_id = s.session_id
         AND r.question_index = s.current_index),
      '[]'::json
    )
  FROM quiz_sessions s
  WHERE s.session_id = p_session_id
$$;

-- sql/functions/get_session_user.sql
-- Session bootstrap lookup by user id
CREATE OR REPLACE FUNCTION get_session_user(p_user_id TEXT)
RETURNS TABLE (
  id         TEXT,
  role       TEXT,
  group_key  TEXT,
  course_ids TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH selected_user AS (
    SELECT
      u.id,
      u.role,
      u.group_key
    FROM public.users u
    WHERE u.id = p_user_id
  ),
  user_courses_agg AS (
    SELECT
      uc.user_id,
      array_agg(uc.course_id ORDER BY uc.course_id) AS course_ids
    FROM public.user_courses uc
    WHERE uc.user_id = p_user_id
    GROUP BY uc.user_id
  )
  SELECT
    su.id,
    su.role,
    su.group_key,
    COALESCE(uca.course_ids, ARRAY[]::TEXT[]) AS course_ids
  FROM selected_user su
  LEFT JOIN user_courses_agg uca
    ON uca.user_id = su.id;
$$;

-- sql/functions/get_user_for_login.sql
-- Login bootstrap lookup by username
DROP FUNCTION IF EXISTS get_user_for_login(TEXT);
CREATE FUNCTION get_user_for_login(p_username TEXT)
RETURNS TABLE (
  id          TEXT,
  role        TEXT,
  group_key   TEXT,
  username    TEXT,
  pin_hash    TEXT,
  enabled     BOOLEAN,
  course_ids  TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH selected_user AS (
    SELECT
      u.id,
      u.role,
      u.group_key,
      u.username,
      u.pin_hash,
      u.enabled
    FROM public.users u
    WHERE LOWER(u.username) = LOWER(p_username)
  ),
  user_courses_agg AS (
    SELECT
      uc.user_id,
      array_agg(uc.course_id ORDER BY uc.course_id) AS course_ids
    FROM public.user_courses uc
    JOIN selected_user su
      ON su.id = uc.user_id
    GROUP BY uc.user_id
  )
  SELECT
    su.id,
    su.role,
    su.group_key,
    su.username,
    su.pin_hash,
    su.enabled,
    COALESCE(uca.course_ids, ARRAY[]::TEXT[]) AS course_ids
  FROM selected_user su
  LEFT JOIN user_courses_agg uca
    ON uca.user_id = su.id;
$$;

-- sql/functions/get_user_username.sql
-- Get username for a user
CREATE OR REPLACE FUNCTION get_user_username(p_user_id TEXT)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT u.username
  FROM public.users u
  WHERE u.id = p_user_id;
$$;

-- sql/functions/set_registration_open_until.sql
-- Set course registration window
CREATE OR REPLACE FUNCTION set_registration_open_until(p_course_id TEXT, p_open_until TIMESTAMPTZ)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  UPDATE public.courses c
  SET registration_open_until = p_open_until,
      updated_at = NOW()
  WHERE c.course_id = p_course_id;
$$;

-- sql/functions/try_advance_quiz_phase.sql
-- Advances a quiz session from 'active' to 'reveal_dist' when all participants
-- have submitted their response for the current question.
-- Called by the student after submitting a response (via anonSQL / direct call).
-- SECURITY DEFINER bypasses RLS so students can trigger the phase update.

CREATE OR REPLACE FUNCTION try_advance_quiz_phase(
  p_session_id     TEXT,
  p_question_index INTEGER
)
RETURNS VOID
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
DECLARE
  v_phase             TEXT;
  v_current_index     INTEGER;
  v_participant_count INTEGER;
  v_response_count    INTEGER;
BEGIN
  -- Only act when the session is actively accepting answers for the right question
  SELECT phase, current_index INTO v_phase, v_current_index
  FROM quiz_sessions
  WHERE session_id = p_session_id;

  IF v_phase IS DISTINCT FROM 'active' THEN
    RETURN;
  END IF;

  -- Ignore stale responses submitted for a previous question
  IF v_current_index IS DISTINCT FROM p_question_index THEN
    RETURN;
  END IF;

  -- Count how many students are in this session
  SELECT COUNT(*) INTO v_participant_count
  FROM quiz_participants
  WHERE session_id = p_session_id;

  -- Count responses for the current question
  SELECT COUNT(*) INTO v_response_count
  FROM quiz_responses
  WHERE session_id = p_session_id
    AND question_index = p_question_index;

  -- Auto-advance only when every participant has answered
  IF v_participant_count > 0 AND v_response_count >= v_participant_count THEN
    UPDATE quiz_sessions
    SET phase      = 'reveal_dist',
        updated_at = now()
    WHERE session_id = p_session_id
      AND phase = 'active'; -- guard against race condition
  END IF;
END;
$$;

-- sql/functions/update_course_progress.sql
-- Update course progress status for topics and chapters
CREATE OR REPLACE FUNCTION update_course_progress(
  p_course_id      TEXT,
  p_new_topic_id   TEXT,
  p_new_chapter_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_topic_order   INTEGER;
  v_chapter_order INTEGER;
BEGIN
  SELECT ct.display_order
  INTO v_topic_order
  FROM public.course_topics ct
  WHERE ct.course_id = p_course_id
    AND ct.topic_id = p_new_topic_id;

  IF v_topic_order IS NULL THEN
    RAISE EXCEPTION 'Topic % is not part of course %', p_new_topic_id, p_course_id
      USING ERRCODE = '22023';
  END IF;

  SELECT cc.display_order
  INTO v_chapter_order
  FROM public.course_chapters cc
  WHERE cc.course_id = p_course_id
    AND cc.topic_id = p_new_topic_id
    AND cc.chapter_id = p_new_chapter_id;

  IF v_chapter_order IS NULL THEN
    RAISE EXCEPTION 'Chapter % is not part of topic % in course %',
      p_new_chapter_id,
      p_new_topic_id,
      p_course_id
      USING ERRCODE = '22023';
  END IF;

  UPDATE public.course_topics
  SET status = 'locked'
  WHERE course_id = p_course_id AND status = 'current';

  UPDATE public.course_topics ct
  SET status = CASE
    WHEN ct.display_order < v_topic_order THEN 'finished'
    WHEN ct.topic_id = p_new_topic_id THEN 'current'
    WHEN ct.display_order = v_topic_order + 1 THEN 'planned'
    ELSE 'locked'
  END
  WHERE ct.course_id = p_course_id;

  UPDATE public.course_chapters
  SET status = 'locked'
  WHERE course_id = p_course_id AND status = 'current';

  UPDATE public.course_chapters cc
  SET status = CASE
    WHEN ct.display_order < v_topic_order THEN 'finished'
    WHEN cc.topic_id = p_new_topic_id AND cc.chapter_id = p_new_chapter_id THEN 'current'
    WHEN cc.topic_id = p_new_topic_id AND cc.display_order < v_chapter_order THEN 'finished'
    ELSE 'locked'
  END
  FROM public.course_topics ct
  WHERE ct.course_id = cc.course_id
    AND ct.topic_id = cc.topic_id
    AND cc.course_id = p_course_id;

  UPDATE public.courses c
  SET updated_at = NOW()
  WHERE c.course_id = p_course_id;
END;
$$;
