-- Generated by @chromatis/base. Edit sql/views/*.sql and sql/functions/*.sql, then regenerate.

-- Drop changed or removed routines
DROP FUNCTION IF EXISTS create_user_with_username(TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS generate_username();

-- sql/functions/create_user_with_username.sql
-- Atomically generate a unique username and create the user account
CREATE OR REPLACE FUNCTION create_user_with_username(
  p_user_id   TEXT,
  p_pin_hash  TEXT,
  p_group_key TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_username        TEXT;
  v_attempts        INTEGER := 0;
  v_constraint_name TEXT;
BEGIN
  LOOP
    v_attempts := v_attempts + 1;

    IF v_attempts > 100 THEN
      RAISE EXCEPTION 'Failed to create user with a unique username after 100 attempts';
    END IF;

    v_username := public.generate_username();

    BEGIN
      PERFORM public.create_user_account(
        p_user_id,
        v_username,
        p_pin_hash,
        p_group_key,
        ARRAY[]::TEXT[]
      );

      RETURN v_username;
    EXCEPTION
      WHEN unique_violation THEN
        GET STACKED DIAGNOSTICS v_constraint_name = CONSTRAINT_NAME;

        IF v_constraint_name = 'users_username_key' THEN
          CONTINUE;
        END IF;

        RAISE;
    END;
  END LOOP;
END;
$$;

-- sql/functions/generate_username.sql
-- Generate a username from a rotating word list and permuted 2-digit suffix
CREATE OR REPLACE FUNCTION generate_username()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  a          CONSTANT INTEGER := 31; -- gcd(31, 101) = 1
  b          CONSTANT INTEGER := 23; -- gcd(23, 99) = 1
  word_count CONSTANT INTEGER := 101; -- gcd(101, 99) = 1
  max_tries  CONSTANT INTEGER := word_count * 99;
  n          BIGINT;
  word_index INTEGER;
  word       TEXT;
  num        TEXT;
  v_username TEXT;
  i          INTEGER;
BEGIN
  FOR i IN 1..max_tries LOOP
    n := nextval('public.username_counter');

    word_index := ((a * n) % word_count)::INTEGER;

    SELECT uw.word
    INTO word
    FROM public.username_words uw
    WHERE uw.pos = word_index;

    IF word IS NULL THEN
      RAISE EXCEPTION 'Missing word at index % (must be contiguous 0..%)',
        word_index, word_count - 1;
    END IF;

    -- Permuted 2-digit number in range 01..99
    num := LPAD((((b * n) % 99) + 1)::TEXT, 2, '0');
    v_username := word || num;

    IF NOT EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.username = v_username
    ) THEN
      RETURN v_username;
    END IF;
  END LOOP;

  RAISE EXCEPTION 'No unused username available in current cycle (word_count=%)', word_count;
END;
$$;
