// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/courses/:courseId": {
    params: {
      "courseId": string;
    };
  };
  "/courses/:courseId/teacher": {
    params: {
      "courseId": string;
    };
  };
  "/courses/:courseId/topics/:topicId/chapters/:chapterId": {
    params: {
      "courseId": string;
      "topicId": string;
      "chapterId": string;
    };
  };
  "/w/:publicKey": {
    params: {
      "publicKey": string;
    };
  };
  "/api/publish": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/courses/:courseId" | "/courses/:courseId/teacher" | "/courses/:courseId/topics/:topicId/chapters/:chapterId" | "/w/:publicKey" | "/api/publish";
  };
  "../src/app/routes/home.tsx": {
    id: "../src/app/routes/home";
    page: "/";
  };
  "../src/app/routes/login.tsx": {
    id: "../src/app/routes/login";
    page: "/login";
  };
  "../src/app/routes/logout.tsx": {
    id: "../src/app/routes/logout";
    page: "/logout";
  };
  "../src/app/routes/course.tsx": {
    id: "../src/app/routes/course";
    page: "/courses/:courseId";
  };
  "../src/app/routes/teacher.tsx": {
    id: "../src/app/routes/teacher";
    page: "/courses/:courseId/teacher";
  };
  "../src/app/routes/chapter.tsx": {
    id: "../src/app/routes/chapter";
    page: "/courses/:courseId/topics/:topicId/chapters/:chapterId";
  };
  "../src/app/routes/worksheet.tsx": {
    id: "../src/app/routes/worksheet";
    page: "/w/:publicKey";
  };
  "../src/app/routes/publish.ts": {
    id: "../src/app/routes/publish";
    page: "/api/publish";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/app/routes/home": unknown;
  "../src/app/routes/login": unknown;
  "../src/app/routes/logout": unknown;
  "../src/app/routes/course": unknown;
  "../src/app/routes/teacher": unknown;
  "../src/app/routes/chapter": unknown;
  "../src/app/routes/worksheet": unknown;
  "../src/app/routes/publish": unknown;
};